tokens = """
{
"lnx"              : {"ti_code": "  13"  , "action": "python_code"           , "statement": "x = math.log(x)"},
"INV lnx"          : {"ti_code": "- 13"  , "action": "python_code"           , "statement": "x = math.exp(x)"},
"CE"               : {"ti_code": "  14"  , "action": "python_code"           , "statement": "x = 0"},
"CLR"              : {"ti_code": "  15"  , "action": "clear"},
"2nd log"          : {"ti_code": "  18"  , "action": "python_code"           , "statement": "x = math.log10(x)"},
"INV 2nd log"      : {"ti_code": "- 18"  , "action": "python_code"           , "statement": "x = math.pow(x, 10)"},
"2nd Ct"           : {"ti_code": "  19"  , "action": "python_code"           , "statement": "sto[7] = 0"},
"INV 2nd Ct"       : {"ti_code": "- 19"  , "action": "clear_all"},
"2nd tan"          : {"ti_code": "  20"  , "action": "python_code"           , "statement": "x = math.tan(unit2rad(x))"},
"INV 2nd tan"      : {"ti_code": "- 20"  , "action": "python_code"           , "statement": "x = rad2unit(math.atan(x))"},
"x<>t"             : {"ti_code": "  22"  , "action": "exchange_memory"       , "number": 7},
"x2"               : {"ti_code": "  23"  , "action": "python_code"           , "statement": "x *= x"},
"V2"               : {"ti_code": "  24"  , "action": "python_code"           , "statement": "x = math.sqrt(x)"},
"1/x"              : {"ti_code": "  25"  , "action": "python_code"           , "statement": "x = 1 / x"},
"2nd D.MS"         : {"ti_code": "  26"  , "action": "python_code"           , "statement": "x = dms2degrees(x)"},
"INV 2nd D.MS"     : {"ti_code": "- 26"  , "action": "python_code"           , "statement": "x = degrees2dms(x)"},
"2nd P->R"         : {"ti_code": "  27"  , "action": "polar_to_rectangular"},
"INV 2nd P->R"     : {"ti_code": "- 27"  , "action": "rectangular_to_polar"},
"2nd sin"          : {"ti_code": "  28"  , "action": "python_code"           , "statement": "x = math.sin(unit2rad(x))"},
"INV 2nd sin"      : {"ti_code": "- 28"  , "action": "python_code"           , "statement": "x = rad2unit(math.asin(x))"},
"2nd cos"          : {"ti_code": "  29"  , "action": "python_code"           , "statement": "x = math.cos(unit2rad(x))"},
"INV 2nd cos"      : {"ti_code": "- 29"  , "action": "python_code"           , "statement": "x = rad2unit(math.acos(x))"},
"2nd pi"           : {"ti_code": "  30"  , "action": "python_code"           , "statement": "x = math.pi"},
"STO 0"            : {"ti_code": "  32 0", "action": "python_code"           , "statement": "sto[0] = x"},
"STO 1"            : {"ti_code": "  32 1", "action": "python_code"           , "statement": "sto[1] = x"},
"STO 2"            : {"ti_code": "  32 2", "action": "python_code"           , "statement": "sto[2] = x"},
"STO 3"            : {"ti_code": "  32 3", "action": "python_code"           , "statement": "sto[3] = x"},
"STO 4"            : {"ti_code": "  32 4", "action": "python_code"           , "statement": "sto[4] = x"},
"STO 5"            : {"ti_code": "  32 5", "action": "python_code"           , "statement": "sto[5] = x"},
"STO 6"            : {"ti_code": "  32 6", "action": "python_code"           , "statement": "sto[6] = x"},
"STO 7"            : {"ti_code": "  32 7", "action": "python_code"           , "statement": "sto[7] = x"},
"RCL 0"            : {"ti_code": "  33 0", "action": "python_code"           , "statement": "x = sto[0]"},
"RCL 1"            : {"ti_code": "  33 1", "action": "python_code"           , "statement": "x = sto[1]"},
"RCL 2"            : {"ti_code": "  33 2", "action": "python_code"           , "statement": "x = sto[2]"},
"RCL 3"            : {"ti_code": "  33 3", "action": "python_code"           , "statement": "x = sto[3]"},
"RCL 4"            : {"ti_code": "  33 4", "action": "python_code"           , "statement": "x = sto[4]"},
"RCL 5"            : {"ti_code": "  33 5", "action": "python_code"           , "statement": "x = sto[5]"},
"RCL 6"            : {"ti_code": "  33 6", "action": "python_code"           , "statement": "x = sto[6]"},
"RCL 7"            : {"ti_code": "  33 7", "action": "python_code"           , "statement": "x = sto[7]"},
"SUM 0"            : {"ti_code": "  34 0", "action": "python_code"           , "statement": "sto[0] += x"},
"SUM 1"            : {"ti_code": "  34 1", "action": "python_code"           , "statement": "sto[1] += x"},
"SUM 2"            : {"ti_code": "  34 2", "action": "python_code"           , "statement": "sto[2] += x"},
"SUM 3"            : {"ti_code": "  34 3", "action": "python_code"           , "statement": "sto[3] += x"},
"SUM 4"            : {"ti_code": "  34 4", "action": "python_code"           , "statement": "sto[4] += x"},
"SUM 5"            : {"ti_code": "  34 5", "action": "python_code"           , "statement": "sto[5] += x"},
"SUM 6"            : {"ti_code": "  34 6", "action": "python_code"           , "statement": "sto[6] += x"},
"SUM 7"            : {"ti_code": "  34 7", "action": "python_code"           , "statement": "sto[7] += x"},
"INV SUM 0"        : {"ti_code": "- 34 0", "action": "python_code"           , "statement": "sto[0] -= x"},
"INV SUM 1"        : {"ti_code": "- 34 1", "action": "python_code"           , "statement": "sto[1] -= x"},
"INV SUM 2"        : {"ti_code": "- 34 2", "action": "python_code"           , "statement": "sto[2] -= x"},
"INV SUM 3"        : {"ti_code": "- 34 3", "action": "python_code"           , "statement": "sto[3] -= x"},
"INV SUM 4"        : {"ti_code": "- 34 4", "action": "python_code"           , "statement": "sto[4] -= x"},
"INV SUM 5"        : {"ti_code": "- 34 5", "action": "python_code"           , "statement": "sto[5] -= x"},
"INV SUM 6"        : {"ti_code": "- 34 6", "action": "python_code"           , "statement": "sto[6] -= x"},
"INV SUM 7"        : {"ti_code": "- 34 7", "action": "python_code"           , "statement": "sto[7] -= x"},
"y^x"              : {"ti_code": "  35"  , "action": "power"                 , "type": "power"},
"INV y^x"          : {"ti_code": "- 35"  , "action": "power"                 , "type": "root"},
"2nd Pause"        : {"ti_code": "  36"  , "action": "python_code"           , "statement": "time.sleep(1)"},
"2nd Exc 7"        : {"ti_code": "  38 7", "action": "exchange_memory"       , "number": 7},
"2nd Prod 0"       : {"ti_code": "  39 0", "action": "python_code"           , "statement": "sto[0] *= x"},
"2nd Prod 1"       : {"ti_code": "  39 1", "action": "python_code"           , "statement": "sto[1] *= x"},
"2nd Prod 2"       : {"ti_code": "  39 2", "action": "python_code"           , "statement": "sto[2] *= x"},
"2nd Prod 3"       : {"ti_code": "  39 3", "action": "python_code"           , "statement": "sto[3] *= x"},
"2nd Prod 4"       : {"ti_code": "  39 4", "action": "python_code"           , "statement": "sto[4] *= x"},
"2nd Prod 5"       : {"ti_code": "  39 5", "action": "python_code"           , "statement": "sto[5] *= x"},
"2nd Prod 6"       : {"ti_code": "  39 6", "action": "python_code"           , "statement": "sto[6] *= x"},
"2nd Prod 7"       : {"ti_code": "  39 7", "action": "python_code"           , "statement": "sto[7] *= x"},
"INV 2nd Prod 0"   : {"ti_code": "- 39 0", "action": "python_code"           , "statement": "sto[0] /= x"},
"INV 2nd Prod 1"   : {"ti_code": "- 39 1", "action": "python_code"           , "statement": "sto[1] /= x"},
"INV 2nd Prod 2"   : {"ti_code": "- 39 2", "action": "python_code"           , "statement": "sto[2] /= x"},
"INV 2nd Prod 3"   : {"ti_code": "- 39 3", "action": "python_code"           , "statement": "sto[3] /= x"},
"INV 2nd Prod 4"   : {"ti_code": "- 39 4", "action": "python_code"           , "statement": "sto[4] /= x"},
"INV 2nd Prod 5"   : {"ti_code": "- 39 5", "action": "python_code"           , "statement": "sto[5] /= x"},
"INV 2nd Prod 6"   : {"ti_code": "- 39 6", "action": "python_code"           , "statement": "sto[6] /= x"},
"INV 2nd Prod 7"   : {"ti_code": "- 39 7", "action": "python_code"           , "statement": "sto[7] /= x"},
"2nd |x|"          : {"ti_code": "  40"  , "action": "python_code"           , "statement": "x = math.abs(x)"},
"EE"               : {"ti_code": "  42"  , "action": "scientific_notation"   , "type": "EE"},
"INV EE"           : {"ti_code": "- 42"  , "action": "python_code"           , "statement": "ee = true"},
"("                : {"ti_code": "  43"  , "action": "open_parenthesis"      , "type": "("},
")"                : {"ti_code": "  44"  , "action": "closing_parenthesis"   , "type": ")"},
"2nd Nop"          : {"ti_code": "  46"  , "action": "python_code"           , "statement": ""},
"2nd Fix"          : {"ti_code": "  48"  , "action": "python_code"           , "statement": "fix = x"},
"INV 2nd Fix"      : {"ti_code": "- 48"  , "action": "python_code"           , "statement": "fix = None"},
"2nd Int"          : {"ti_code": "  49"  , "action": "python_code"           , "statement": "x = int(x)"},
"INV 2nd Int"      : {"ti_code": "- 49"  , "action": "python_code"           , "statement": "x = x - int(x)"},
"2nd Deg"          : {"ti_code": "  50"  , "action": "python_code"           , "statement": "unit = 'Deg'"},
"GTO 0"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_0"},
"GTO 1"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_1"},
"GTO 2"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_2"},
"GTO 3"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_3"},
"GTO 4"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_4"},
"GTO 5"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_5"},
"GTO 6"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_6"},
"GTO 7"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_7"},
"GTO 8"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_8"},
"GTO 9"            : {"ti_code": "  51 0", "action": "python_code"           , "statement": "goto .label_9"},
"*"                : {"ti_code": "  55"  , "action": "multiplication"        , "type": "*"},
"2nd Dsz"          : {"ti_code": "  56"  , "action": "decrement_skip_on_zero", "statement": "if sto[0] != 0:"},
"INV 2nd Dsz"      : {"ti_code": "- 56"  , "action": "decrement_skip_on_zero", "statement": "if sto[0] == 0:"},
"2nd Rad"          : {"ti_code": "  60"  , "action": "python_code"           , "statement": "unit = 'Rad'"},
"SBR 0"            : {"ti_code": "  61 0", "action": "python_code"           , "statement": "sbr_0()"},
"SBR 1"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_1()"},
"SBR 2"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_2()"},
"SBR 3"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_3()"},
"SBR 4"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_4()"},
"SBR 5"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_5()"},
"SBR 6"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_6()"},
"SBR 7"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_7()"},
"SBR 8"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_8()"},
"SBR 9"            : {"ti_code": "  61 1", "action": "python_code"           , "statement": "sbr_9()"},
"INV SBR"          : {"ti_code": "- 61"  , "action": "php_code"},
"2nd x=t"          : {"ti_code": "  66"  , "action": "python_code"           , "statement": "if x == sto[7]:"},
"INV 2nd x=t"      : {"ti_code": "- 66"  , "action": "python_code"           , "statement": "if x != sto[7]:"},
"2nd Grd"          : {"ti_code": "  70"  , "action": "python_code"           , "statement": "unit = 'Grd'"},
"RST"              : {"ti_code": "  71"},
"2nd x>=t"         : {"ti_code": "  76"  , "action": "python_code"           , "statement": "if x >= sto[7]:"},
"INV 2nd x>=t"     : {"ti_code": "- 76"  , "action": "python_code"           , "statement": "if x < sto[7]:"},
"2nd s2"           : {"ti_code": "  80"  , "action": "python_code"           , "statement": "x = (sto[2] - sto[1] * sto[1] / sto[0]) / sto[0])"}, # var(Y) = sum(Y^2) / N - avg(Y)
"INV 2nd s2"       : {"ti_code": "- 80"  , "action": "python_code"           , "statement": "x = (sto[4] - sto[3] * sto[3] / sto[0]) / sto[0])"}, # var(X) = sum(X^2) / N - avg(X)
"R/S"              : {"ti_code": "  81"},
#"."               : {"ti_code": "  83"}, # Not a token as a single character
"+/-"              : {"ti_code": "  84"  , "action": "python_code"           , "statement": "x = -x"},
"="                : {"ti_code": "  85"  , "action": "equality"              , "type": "="},
"2nd Lbl 0"        : {"ti_code": "  86 0", "action": "python_code"           , "statement": "label .label_0"},
"2nd Lbl 1"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_1"},
"2nd Lbl 2"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_2"},
"2nd Lbl 3"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_3"},
"2nd Lbl 4"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_4"},
"2nd Lbl 5"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_5"},
"2nd Lbl 6"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_6"},
"2nd Lbl 7"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_7"},
"2nd Lbl 8"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_8"},
"2nd Lbl 9"        : {"ti_code": "  86 1", "action": "python_code"           , "statement": "label .label_9"},
"2nd S+"           : {"ti_code": "  88"  , "action": "sum"},
"INV 2nd S+"       : {"ti_code": "- 88"},
"2nd x"            : {"ti_code": "  89"  , "action": "python_code"           , "statement": "x = sto[1] / sto[0]"}, # avg(Y) = sum(Y) / N
"INV 2nd x"        : {"ti_code": "- 89"  , "action": "python_code"           , "statement": "x = sto[3] / sto[0]"}, # avg(X) = sum(X) / N

# Operators must be after the tokens because some of them use them, ex. "+/-"
"/"                : {"ti_code": "  45"  , "action": "multiplication"        , "type": "/"},
"-"                : {"ti_code": "  65"  , "action": "addition"              , "type": "-"},
"+"                : {"ti_code": "  75"  , "action": "addition"              , "type": "+"},
}
"""

tokens = eval(tokens)
